# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $UDACITY_PROJECT # UDACITY_PROJECT
            echo $MY_NAME # MY_NAME
            echo $MY_CITY # MY_CITY
            
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
      - run: echo My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>.
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
